name: MP Deploy

on:
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npx lerna bootstrap

      - name: Build
        run: npx lerna run build

      - name: Deploy
        env:
          UPLOAD_PRIVATE_KEY: ${{ secrets.MPDEPLOYKEY }}
        run: |
          echo "$UPLOAD_PRIVATE_KEY" > private.key
          npx miniprogram-ci preview --appid wx9fc6778640e4fa4f --pp ./packages/mp/dist/ --pkp ./private.key -r 1 --uv 0.0.1
